name: "Auto Release"
on:
  pull_request:
    types:
      - closed

jobs:
  auto-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'dependabot[bot]' && (contains(github.event.pull_request.labels.*.name, 'docker') || contains(github.event.pull_request.labels.*.name, 'go'))

    name: "Auto Release"
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Get Version
        id: get-version
        env:
          HAS_DOCKER_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'docker') }}
          HAS_GO_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'go') }}
        run: |
          if [[ "$HAS_DOCKER_LABEL" == 'true' ]]; then
            echo "version=$(grep FROM ./Dockerfile | tail -n1 | cut -d':' -f2 | cut -d' ' -f1 | xargs)-0" >> $GITHUB_OUTPUT
          elif [[ "$HAS_GO_LABEL" == 'true' ]]; then
            LATEST_TAG=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.name')
            # Increment the patch version (last number after the last dot)
            NEW_VERSION=$(echo "$LATEST_TAG" | awk -F- -v OFS=- '{$NF++; print}')
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Unknown trigger: no docker or go label found"
            exit 1
          fi
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Release
        run: gh release create ${{ steps.get-version.outputs.version }} --generate-notes
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
